[project]
name = "fands2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.115.12",
    "sqlmodel>=0.0.24",
]

[dependency-groups]
dev = [
    "fastapi>=0.115.12",
    "pytest>=8.3.5",
]
